// gui/update.cpp - see update.h.

#include "gui/update.h"

#if __has_include("g2c_version.h")
#include "g2c_version.h"   // generated by CMake into the build directory
#endif
#ifndef G2C_VERSION
#define G2C_VERSION "dev"
#endif
#ifndef G2C_COMMIT
#define G2C_COMMIT ""
#endif

#include <algorithm>
#include <array>
#include <cctype>
#include <chrono>
#include <fstream>

namespace g2::gui::update {
namespace fs = std::filesystem;

namespace {

bool startsWith(std::string_view s, std::string_view prefix) {
    return s.size() >= prefix.size() && s.substr(0, prefix.size()) == prefix;
}

bool iequals(std::string_view a, std::string_view b) {
    if (a.size() != b.size()) return false;
    for (std::size_t i = 0; i < a.size(); ++i)
        if (std::tolower(static_cast<unsigned char>(a[i])) !=
            std::tolower(static_cast<unsigned char>(b[i])))
            return false;
    return true;
}

// --- Minimal JSON reader ----------------------------------------------------
//
// Just enough for the GitHub release object: objects, arrays, strings with
// escapes, numbers, true/false/null. A release is a few kilobytes; a general
// library would be the largest dependency of the whole program for it.
//
// Depth is limited, so a hostile answer can't exhaust the stack.
struct Json {
    enum class Type { Null, Bool, Number, String, Array, Object };
    Type                                    type = Type::Null;
    bool                                    boolean = false;
    double                                  number = 0.0;
    std::string                             string;
    std::vector<Json>                       array;
    std::vector<std::pair<std::string, Json>> object;

    const Json* get(std::string_view key) const {
        if (type != Type::Object) return nullptr;
        for (const auto& [k, v] : object)
            if (k == key) return &v;
        return nullptr;
    }
    std::string str(std::string_view key) const {
        const Json* v = get(key);
        return v && v->type == Type::String ? v->string : std::string();
    }
};

class JsonParser {
public:
    explicit JsonParser(std::string_view text) : s_(text) {}

    std::optional<Json> parse() {
        Json v;
        if (!value(v, 0)) return std::nullopt;
        skipSpace();
        if (pos_ != s_.size()) return std::nullopt;
        return v;
    }

private:
    static constexpr int kMaxDepth = 64;

    void skipSpace() {
        while (pos_ < s_.size() &&
               (s_[pos_] == ' ' || s_[pos_] == '\t' || s_[pos_] == '\n' || s_[pos_] == '\r'))
            ++pos_;
    }

    bool literal(std::string_view word) {
        if (s_.substr(pos_, word.size()) != word) return false;
        pos_ += word.size();
        return true;
    }

    bool value(Json& out, int depth) {
        if (depth > kMaxDepth) return false;
        skipSpace();
        if (pos_ >= s_.size()) return false;
        switch (s_[pos_]) {
            case '{': return object(out, depth);
            case '[': return array(out, depth);
            case '"': out.type = Json::Type::String; return string(out.string);
            case 't': out.type = Json::Type::Bool; out.boolean = true; return literal("true");
            case 'f': out.type = Json::Type::Bool; return literal("false");
            case 'n': return literal("null");
            default: return number(out);
        }
    }

    bool object(Json& out, int depth) {
        out.type = Json::Type::Object;
        ++pos_;
        skipSpace();
        if (pos_ < s_.size() && s_[pos_] == '}') { ++pos_; return true; }
        for (;;) {
            skipSpace();
            std::string key;
            if (pos_ >= s_.size() || s_[pos_] != '"' || !string(key)) return false;
            skipSpace();
            if (pos_ >= s_.size() || s_[pos_] != ':') return false;
            ++pos_;
            Json v;
            if (!value(v, depth + 1)) return false;
            out.object.emplace_back(std::move(key), std::move(v));
            skipSpace();
            if (pos_ >= s_.size()) return false;
            if (s_[pos_] == '}') { ++pos_; return true; }
            if (s_[pos_] != ',') return false;
            ++pos_;
        }
    }

    bool array(Json& out, int depth) {
        out.type = Json::Type::Array;
        ++pos_;
        skipSpace();
        if (pos_ < s_.size() && s_[pos_] == ']') { ++pos_; return true; }
        for (;;) {
            Json v;
            if (!value(v, depth + 1)) return false;
            out.array.push_back(std::move(v));
            skipSpace();
            if (pos_ >= s_.size()) return false;
            if (s_[pos_] == ']') { ++pos_; return true; }
            if (s_[pos_] != ',') return false;
            ++pos_;
        }
    }

    bool number(Json& out) {
        const std::size_t start = pos_;
        if (pos_ < s_.size() && s_[pos_] == '-') ++pos_;
        bool digits = false;
        while (pos_ < s_.size() && (std::isdigit(static_cast<unsigned char>(s_[pos_])) ||
                                    s_[pos_] == '.' || s_[pos_] == 'e' || s_[pos_] == 'E' ||
                                    s_[pos_] == '+' || s_[pos_] == '-')) {
            digits = digits || std::isdigit(static_cast<unsigned char>(s_[pos_]));
            ++pos_;
        }
        if (!digits) return false;
        out.type = Json::Type::Number;
        try {
            out.number = std::stod(std::string(s_.substr(start, pos_ - start)));
        } catch (...) {
            return false;
        }
        return true;
    }

    bool hex4(unsigned& out) {
        if (pos_ + 4 > s_.size()) return false;
        out = 0;
        for (int i = 0; i < 4; ++i) {
            const char c = s_[pos_++];
            out <<= 4;
            if (c >= '0' && c <= '9') out |= static_cast<unsigned>(c - '0');
            else if (c >= 'a' && c <= 'f') out |= static_cast<unsigned>(c - 'a' + 10);
            else if (c >= 'A' && c <= 'F') out |= static_cast<unsigned>(c - 'A' + 10);
            else return false;
        }
        return true;
    }

    static void appendUtf8(std::string& s, unsigned cp) {
        if (cp < 0x80) {
            s.push_back(static_cast<char>(cp));
        } else if (cp < 0x800) {
            s.push_back(static_cast<char>(0xC0 | (cp >> 6)));
            s.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
        } else if (cp < 0x10000) {
            s.push_back(static_cast<char>(0xE0 | (cp >> 12)));
            s.push_back(static_cast<char>(0x80 | ((cp >> 6) & 0x3F)));
            s.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
        } else {
            s.push_back(static_cast<char>(0xF0 | (cp >> 18)));
            s.push_back(static_cast<char>(0x80 | ((cp >> 12) & 0x3F)));
            s.push_back(static_cast<char>(0x80 | ((cp >> 6) & 0x3F)));
            s.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
        }
    }

    bool string(std::string& out) {
        ++pos_;   // opening quote
        while (pos_ < s_.size()) {
            const char c = s_[pos_++];
            if (c == '"') return true;
            if (static_cast<unsigned char>(c) < 0x20) return false;
            if (c != '\\') { out.push_back(c); continue; }
            if (pos_ >= s_.size()) return false;
            const char e = s_[pos_++];
            switch (e) {
                case '"': out.push_back('"'); break;
                case '\\': out.push_back('\\'); break;
                case '/': out.push_back('/'); break;
                case 'b': out.push_back('\b'); break;
                case 'f': out.push_back('\f'); break;
                case 'n': out.push_back('\n'); break;
                case 'r': out.push_back('\r'); break;
                case 't': out.push_back('\t'); break;
                case 'u': {
                    unsigned cp = 0;
                    if (!hex4(cp)) return false;
                    // Surrogate pair: emoji and the like in release notes.
                    if (cp >= 0xD800 && cp < 0xDC00) {
                        unsigned lo = 0;
                        if (pos_ + 2 > s_.size() || s_[pos_] != '\\' || s_[pos_ + 1] != 'u')
                            return false;
                        pos_ += 2;
                        if (!hex4(lo) || lo < 0xDC00 || lo >= 0xE000) return false;
                        cp = 0x10000 + ((cp - 0xD800) << 10) + (lo - 0xDC00);
                    } else if (cp >= 0xDC00 && cp < 0xE000) {
                        return false;
                    }
                    appendUtf8(out, cp);
                    break;
                }
                default: return false;
            }
        }
        return false;
    }

    std::string_view s_;
    std::size_t      pos_ = 0;
};

// --- SHA-256 (FIPS 180-4) ---------------------------------------------------
//
// Windows has one in BCrypt, but this one runs in the tests on every system
// and is checked there against the published test vectors.
class Sha256 {
public:
    void update(const unsigned char* data, std::size_t n) {
        for (std::size_t i = 0; i < n; ++i) {
            block_[fill_++] = data[i];
            if (fill_ == 64) {
                compress();
                fill_ = 0;
            }
        }
        bits_ += static_cast<std::uint64_t>(n) * 8;
    }

    std::string hex() {
        const std::uint64_t bits = bits_;
        const unsigned char one = 0x80, zero = 0;
        update(&one, 1);
        while (fill_ != 56) update(&zero, 1);
        unsigned char len[8];
        for (int i = 0; i < 8; ++i) len[i] = static_cast<unsigned char>(bits >> (56 - 8 * i));
        update(len, 8);
        static const char* digits = "0123456789abcdef";
        std::string out;
        for (const std::uint32_t w : h_)
            for (int i = 28; i >= 0; i -= 4) out.push_back(digits[(w >> i) & 0xF]);
        return out;
    }

private:
    static std::uint32_t rotr(std::uint32_t x, int n) { return (x >> n) | (x << (32 - n)); }

    void compress() {
        static constexpr std::uint32_t k[64] = {
            0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4,
            0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe,
            0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f,
            0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
            0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc,
            0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
            0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116,
            0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
            0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7,
            0xc67178f2};
        std::uint32_t w[64];
        for (int i = 0; i < 16; ++i)
            w[i] = static_cast<std::uint32_t>(block_[4 * i]) << 24 |
                   static_cast<std::uint32_t>(block_[4 * i + 1]) << 16 |
                   static_cast<std::uint32_t>(block_[4 * i + 2]) << 8 |
                   static_cast<std::uint32_t>(block_[4 * i + 3]);
        for (int i = 16; i < 64; ++i) {
            const std::uint32_t s0 = rotr(w[i - 15], 7) ^ rotr(w[i - 15], 18) ^ (w[i - 15] >> 3);
            const std::uint32_t s1 = rotr(w[i - 2], 17) ^ rotr(w[i - 2], 19) ^ (w[i - 2] >> 10);
            w[i] = w[i - 16] + s0 + w[i - 7] + s1;
        }
        std::uint32_t a = h_[0], b = h_[1], c = h_[2], d = h_[3], e = h_[4], f = h_[5],
                      g = h_[6], h = h_[7];
        for (int i = 0; i < 64; ++i) {
            const std::uint32_t t1 =
                h + (rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25)) + ((e & f) ^ (~e & g)) + k[i] + w[i];
            const std::uint32_t t2 =
                (rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22)) + ((a & b) ^ (a & c) ^ (b & c));
            h = g; g = f; f = e; e = d + t1;
            d = c; c = b; b = a; a = t1 + t2;
        }
        h_[0] += a; h_[1] += b; h_[2] += c; h_[3] += d;
        h_[4] += e; h_[5] += f; h_[6] += g; h_[7] += h;
    }

    std::array<std::uint32_t, 8> h_ = {0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a,
                                        0x510e527f, 0x9b05688c, 0x1f83d9ab, 0x5be0cd19};
    unsigned char                 block_[64] = {};
    std::size_t                   fill_ = 0;
    std::uint64_t                 bits_ = 0;
};

// Pre-release identifiers compare numerically if both are numbers,
// otherwise as text; a number ranks below text (semver 2.0, section 11).
int comparePre(std::string_view a, std::string_view b) {
    if (a.empty() || b.empty()) return a.empty() == b.empty() ? 0 : (a.empty() ? 1 : -1);
    const auto isNum = [](std::string_view s) {
        return !s.empty() && std::all_of(s.begin(), s.end(), [](char c) {
            return std::isdigit(static_cast<unsigned char>(c)) != 0;
        });
    };
    while (!a.empty() || !b.empty()) {
        if (a.empty()) return -1;
        if (b.empty()) return 1;
        const std::size_t da = a.find('.'), db = b.find('.');
        const std::string_view pa = a.substr(0, da), pb = b.substr(0, db);
        a = da == std::string_view::npos ? std::string_view() : a.substr(da + 1);
        b = db == std::string_view::npos ? std::string_view() : b.substr(db + 1);
        const bool na = isNum(pa), nb = isNum(pb);
        if (na && nb) {
            if (pa.size() != pb.size()) return pa.size() < pb.size() ? -1 : 1;
            if (pa != pb) return pa < pb ? -1 : 1;
        } else if (na != nb) {
            return na ? -1 : 1;
        } else if (pa != pb) {
            return pa < pb ? -1 : 1;
        }
    }
    return 0;
}

std::string shortCommit(std::string_view c) { return std::string(c.substr(0, 7)); }

}  // namespace

// --- Version ----------------------------------------------------------------

BuildInfo thisBuild() { return {G2C_VERSION, G2C_COMMIT}; }

BuildKind kindOf(const BuildInfo& b) {
    if (startsWith(b.version, "snapshot")) return BuildKind::Snapshot;
    if (parseVersion(b.version)) return BuildKind::Release;
    return BuildKind::Dev;
}

std::optional<Version> parseVersion(std::string_view t) {
    if (!t.empty() && (t[0] == 'v' || t[0] == 'V')) t.remove_prefix(1);
    // Build metadata ("+abc") has no precedence.
    if (const std::size_t plus = t.find('+'); plus != std::string_view::npos) t = t.substr(0, plus);
    Version v;
    if (const std::size_t dash = t.find('-'); dash != std::string_view::npos) {
        v.pre = std::string(t.substr(dash + 1));
        if (v.pre.empty()) return std::nullopt;
        t = t.substr(0, dash);
    }
    int* parts[3] = {&v.major, &v.minor, &v.patch};
    for (int i = 0; i < 3; ++i) {
        std::size_t n = 0;
        while (n < t.size() && std::isdigit(static_cast<unsigned char>(t[n]))) ++n;
        // Nine digits at most, so the int can't overflow.
        if (n == 0 || n > 9) return std::nullopt;
        *parts[i] = std::stoi(std::string(t.substr(0, n)));
        t.remove_prefix(n);
        if (i < 2) {
            if (t.empty() || t[0] != '.') return std::nullopt;
            t.remove_prefix(1);
        }
    }
    if (!t.empty()) return std::nullopt;
    return v;
}

int compare(const Version& a, const Version& b) {
    if (a.major != b.major) return a.major < b.major ? -1 : 1;
    if (a.minor != b.minor) return a.minor < b.minor ? -1 : 1;
    if (a.patch != b.patch) return a.patch < b.patch ? -1 : 1;
    return comparePre(a.pre, b.pre);
}

// --- Release ------------------------------------------------------------------

const Asset* Release::find(std::string_view assetName) const {
    for (const auto& a : assets)
        if (iequals(a.name, assetName)) return &a;
    return nullptr;
}

std::optional<Release> parseRelease(std::string_view json) {
    const auto doc = JsonParser(json).parse();
    if (!doc || doc->type != Json::Type::Object) return std::nullopt;
    Release r;
    r.tag = doc->str("tag_name");
    if (r.tag.empty()) return std::nullopt;
    r.name = doc->str("name");
    r.htmlUrl = doc->str("html_url");
    r.commit = doc->str("target_commitish");
    r.notes = doc->str("body");
    if (const Json* p = doc->get("prerelease"); p && p->type == Json::Type::Bool)
        r.prerelease = p->boolean;
    if (const Json* list = doc->get("assets"); list && list->type == Json::Type::Array) {
        for (const auto& a : list->array) {
            Asset asset;
            asset.name = a.str("name");
            asset.url = a.str("browser_download_url");
            if (const Json* s = a.get("size"); s && s->type == Json::Type::Number && s->number >= 0)
                asset.size = static_cast<std::uint64_t>(s->number);
            if (!asset.name.empty() && !asset.url.empty()) r.assets.push_back(std::move(asset));
        }
    }
    return r;
}

Channel defaultChannel(const BuildInfo& b) {
    return kindOf(b) == BuildKind::Snapshot ? Channel::Snapshot : Channel::Stable;
}

std::string apiUrl(Channel ch) {
    // /releases/latest never returns a pre-release, so the snapshot has to be
    // asked for by its tag.
    return std::string("https://api.github.com/repos/") + kRepo +
           (ch == Channel::Stable ? "/releases/latest" : "/releases/tags/snapshot");
}

std::string releaseId(const Release& r, Channel ch) {
    return ch == Channel::Snapshot ? r.commit : r.tag;
}

std::string displayName(const Release& r, Channel ch) {
    if (ch == Channel::Snapshot) return "snapshot " + shortCommit(r.commit);
    return !r.tag.empty() && (r.tag[0] == 'v' || r.tag[0] == 'V') ? r.tag.substr(1) : r.tag;
}

std::string displayName(const BuildInfo& b) {
    if (kindOf(b) == BuildKind::Snapshot && !b.commit.empty())
        return "snapshot " + shortCommit(b.commit);
    return b.version;
}

bool isNewer(const BuildInfo& own, const Release& r, Channel ch) {
    if (ch == Channel::Snapshot) {
        if (r.commit.empty()) return false;
        if (own.commit.empty()) return true;
        // Either side may be abbreviated.
        return !startsWith(r.commit, own.commit) && !startsWith(own.commit, r.commit);
    }
    if (r.prerelease) return false;
    const auto remote = parseVersion(r.tag);
    if (!remote) return false;
    const auto mine = parseVersion(own.version);
    // A snapshot or dev build has no number to compare. Whoever chose the
    // stable channel on it wants the stable version.
    if (!mine) return true;
    return compare(*remote, *mine) > 0;
}

bool trustedDownloadUrl(std::string_view url) {
    const std::string prefix = std::string("https://github.com/") + kRepo + "/releases/download/";
    if (url.size() <= prefix.size() || !iequals(url.substr(0, prefix.size()), prefix)) return false;
    // No way out of the release folder.
    return url.find("..") == std::string_view::npos && url.find('\\') == std::string_view::npos;
}

// --- Integrity ----------------------------------------------------------------

std::string sha256Hex(std::string_view data) {
    Sha256 h;
    h.update(reinterpret_cast<const unsigned char*>(data.data()), data.size());
    return h.hex();
}

std::optional<std::string> sha256File(const fs::path& path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) return std::nullopt;
    Sha256 h;
    std::vector<char> buf(1 << 16);
    while (f) {
        f.read(buf.data(), static_cast<std::streamsize>(buf.size()));
        const std::streamsize n = f.gcount();
        if (n > 0) h.update(reinterpret_cast<const unsigned char*>(buf.data()), static_cast<std::size_t>(n));
    }
    if (f.bad()) return std::nullopt;
    return h.hex();
}

std::optional<std::string> checksumFor(std::string_view sums, std::string_view file) {
    while (!sums.empty()) {
        const std::size_t nl = sums.find('\n');
        std::string_view line = sums.substr(0, nl);
        sums = nl == std::string_view::npos ? std::string_view() : sums.substr(nl + 1);
        while (!line.empty() && (line.back() == '\r' || line.back() == ' ')) line.remove_suffix(1);
        if (line.size() < 66) continue;
        const std::string_view hash = line.substr(0, 64);
        if (!std::all_of(hash.begin(), hash.end(),
                         [](char c) { return std::isxdigit(static_cast<unsigned char>(c)) != 0; }))
            continue;
        std::string_view name = line.substr(64);
        if (name.empty() || (name[0] != ' ' && name[0] != '\t')) continue;
        while (!name.empty() && (name[0] == ' ' || name[0] == '\t')) name.remove_prefix(1);
        if (!name.empty() && name[0] == '*') name.remove_prefix(1);   // binary mode marker
        if (startsWith(name, "./")) name.remove_prefix(2);
        if (!iequals(name, file)) continue;
        std::string out(hash);
        for (char& c : out) c = static_cast<char>(std::tolower(static_cast<unsigned char>(c)));
        return out;
    }
    return std::nullopt;
}

// --- Swapping the executable --------------------------------------------------

fs::path oldPathOf(const fs::path& exe) {
    fs::path p = exe;
    p += ".old";
    return p;
}

std::string replaceFile(const fs::path& target, const fs::path& staged) {
    std::error_code ec;
    const fs::path old = oldPathOf(target);
    fs::remove(old, ec);
    if (fs::exists(old, ec)) return "cannot remove " + old.filename().string();

    const bool hadTarget = fs::exists(target, ec);
    if (hadTarget) {
        fs::rename(target, old, ec);
        if (ec) return ec.message();
    }
    fs::rename(staged, target, ec);
    if (ec) {
        const std::string why = ec.message();
        std::error_code undo;
        if (hadTarget) fs::rename(old, target, undo);
        // Undo failed as well: the exe is only there as .old now. Try a copy
        // instead of a rename; if even that fails, say exactly where things are.
        if (hadTarget && (undo || !fs::exists(target, undo))) {
            std::error_code cp;
            fs::copy_file(old, target, fs::copy_options::overwrite_existing, cp);
            if (cp || !fs::exists(target, cp))
                return why + " - " + target.filename().string() + " liegt jetzt als " +
                       old.filename().string() + " daneben";
        }
        return why;
    }
    return {};
}

bool cleanupAfterUpdate(const fs::path& exe) {
    bool found = false;
    for (const fs::path& p : {exe, exe.parent_path() / "g2c-cli.exe"}) {
        const fs::path old = oldPathOf(p);
        std::error_code ec;
        if (!fs::exists(old, ec)) continue;
        found = true;
        // The old process launched this one as its very last step and may
        // still hold its image file for a few milliseconds.
        for (int attempt = 0; attempt < 25; ++attempt) {
            if (fs::remove(old, ec) || !fs::exists(old, ec)) break;
            std::this_thread::sleep_for(std::chrono::milliseconds(200));
        }
    }
    return found;
}

// --- Updater ------------------------------------------------------------------

Updater::Updater(Network net, BuildInfo build, fs::path exePath)
    : net_(std::move(net)), build_(std::move(build)), exe_(std::move(exePath)) {
    std::error_code ec;
    justUpdated_ = !exe_.empty() && fs::exists(oldPathOf(exe_), ec);
}

Updater::~Updater() {
    cancel_.store(true);
    if (worker_.joinable()) worker_.join();
}

void Updater::wait() {
    if (worker_.joinable()) worker_.join();
}

bool Updater::busy() const {
    std::lock_guard lock(mutex_);
    return status_.phase == Phase::Checking || status_.phase == Phase::Downloading;
}

Status Updater::status() const {
    std::lock_guard lock(mutex_);
    Status s = status_;
    s.done = done_.load();
    s.total = total_.load();
    return s;
}

void Updater::set(Phase p) {
    std::lock_guard lock(mutex_);
    status_.phase = p;
}

void Updater::fail(Error e, std::string detail) {
    std::lock_guard lock(mutex_);
    status_.phase = Phase::Failed;
    status_.error = e;
    status_.detail = std::move(detail);
}

void Updater::dismiss() {
    if (busy()) return;
    std::lock_guard lock(mutex_);
    status_.phase = Phase::Idle;
    status_.error = Error::None;
    status_.detail.clear();
}

void Updater::launch(std::function<void()> fn) {
    if (worker_.joinable()) worker_.join();
    cancel_.store(false);
    worker_ = std::thread(std::move(fn));
}

void Updater::startup(bool autoCheck, Channel ch) {
    if (busy()) return;
    if (autoCheck) {
        std::lock_guard lock(mutex_);
        status_ = Status{};
        status_.phase = Phase::Checking;
    }
    launch([this, autoCheck, ch] {
        if (justUpdated_) cleanupAfterUpdate(exe_);
        if (autoCheck) runCheck(ch);
    });
}

void Updater::check(Channel ch, bool manual) {
    if (busy() || !net_.get) return;
    {
        std::lock_guard lock(mutex_);
        status_ = Status{};
        status_.phase = Phase::Checking;
        status_.manual = manual;
    }
    launch([this, ch] { runCheck(ch); });
}

void Updater::runCheck(Channel ch) {
    if (!net_.get) return fail(Error::Network, "no network support");
    const HttpResult res = net_.get(apiUrl(ch), 1u << 20);
    if (res.status == 0) return fail(Error::Network, res.error);
    if (res.status == 404) return fail(Error::NoRelease);
    if (res.status != 200) return fail(Error::Network, "HTTP " + std::to_string(res.status));
    auto rel = parseRelease(res.body);
    if (!rel) return fail(Error::BadAnswer);
    bool newer = isNewer(build_, *rel, ch);
    std::lock_guard lock(mutex_);
    // Already installed in this session and only waiting for the restart:
    // offering it again downloaded everything and then failed on the
    // locked .old file.
    if (newer && !installedId_.empty() && rel->tag + "|" + rel->commit == installedId_) {
        status_.release = std::move(*rel);
        status_.phase = Phase::Installed;
        return;
    }
    status_.release = std::move(*rel);
    status_.phase = newer ? Phase::Available : Phase::UpToDate;
}

void Updater::install() {
    Release r;
    {
        std::lock_guard lock(mutex_);
        if (status_.phase != Phase::Available || !net_.download || exe_.empty()) return;
        status_.phase = Phase::Downloading;
        // Installing is always the user's doing: its errors are shown.
        status_.manual = true;
        r = status_.release;
    }
    done_.store(0);
    total_.store(0);
    launch([this, r = std::move(r)]() mutable { runInstall(std::move(r)); });
}

bool Updater::fetchVerified(const Asset& a, const std::string& sums, const fs::path& dest,
                            std::uint64_t base) {
    std::error_code ec;
    const auto expected = checksumFor(sums, a.name);
    if (!expected) {
        fail(Error::NoAsset, a.name);
        return false;
    }
    const std::string err = net_.download(a.url, dest, [&](std::uint64_t done, std::uint64_t) {
        done_.store(base + done);
        return !cancel_.load();
    });
    const auto discard = [&](Error e, std::string detail) {
        fs::remove(dest, ec);
        fail(e, std::move(detail));
        return false;
    };
    if (cancel_.load()) return discard(Error::Cancelled, {});
    // "write:" from the platform = the target folder is not writable
    // (Program Files). That is not a connection problem.
    if (err.rfind("write:", 0) == 0) return discard(Error::Write, err.substr(6));
    if (!err.empty()) return discard(Error::Network, err);

    const std::uint64_t size = fs::file_size(dest, ec);
    if (ec || (a.size && size != a.size))
        return discard(Error::Checksum, a.name + ": size " + std::to_string(size));

    // Every Windows executable starts with "MZ". An HTML error page that
    // slipped through as HTTP 200 does not.
    char mz[2] = {};
    {
        std::ifstream f(dest, std::ios::binary);
        f.read(mz, 2);
    }
    if (mz[0] != 'M' || mz[1] != 'Z') return discard(Error::Checksum, a.name + ": not an .exe");

    const auto actual = sha256File(dest);
    if (!actual || *actual != *expected) return discard(Error::Checksum, a.name + ": SHA-256");
    return true;
}

void Updater::runInstall(Release r) {
    const Asset* main = r.find("g2c.exe");
    const Asset* sumsAsset = r.find("SHA256SUMS.txt");
    if (!main || !sumsAsset) return fail(Error::NoAsset, !main ? "g2c.exe" : "SHA256SUMS.txt");

    // The command-line exe from the zip, if it sits next to this one.
    std::error_code ec;
    const fs::path cliPath = exe_.parent_path() / "g2c-cli.exe";
    const Asset*   cli = fs::exists(cliPath, ec) && !iequals(exe_.filename().string(), "g2c-cli.exe")
                             ? r.find("g2c-cli.exe")
                             : nullptr;

    for (const Asset* a : {main, sumsAsset, cli})
        if (a && !trustedDownloadUrl(a->url)) return fail(Error::Untrusted, a->url);

    const HttpResult sums = net_.get(sumsAsset->url, 64u * 1024u);
    if (sums.status == 0) return fail(Error::Network, sums.error);
    if (sums.status != 200) return fail(Error::Network, "HTTP " + std::to_string(sums.status));

    total_.store(main->size + (cli ? cli->size : 0));

    // Staged next to the target: same volume, so the final rename is atomic.
    fs::path stagedMain = exe_;
    stagedMain += ".download";
    if (!fetchVerified(*main, sums.body, stagedMain, 0)) return;

    fs::path stagedCli = cliPath;
    stagedCli += ".download";
    if (cli && !fetchVerified(*cli, sums.body, stagedCli, main->size)) {
        fs::remove(stagedMain, ec);
        return;
    }

    if (const std::string err = replaceFile(exe_, stagedMain); !err.empty()) {
        // Keep the verified new file if the exe is gone - it is then the only
        // working copy (the old code deleted it).
        if (fs::exists(exe_, ec)) fs::remove(stagedMain, ec);
        fs::remove(stagedCli, ec);
        return fail(Error::Write, err);
    }
    // The main exe is the one that matters. If only the command-line copy
    // can't be replaced, say so, but the update itself has worked.
    std::string note;
    if (cli) {
        if (const std::string err = replaceFile(cliPath, stagedCli); !err.empty()) {
            fs::remove(stagedCli, ec);
            note = "g2c-cli.exe: " + err;
        }
    }
    std::lock_guard lock(mutex_);
    status_.phase = Phase::Installed;
    status_.detail = std::move(note);
    installedId_ = r.tag + "|" + r.commit;
}

}  // namespace g2::gui::update
